[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[modules.dagger-dang-sdk.as-sdk]
name = "dang"

[[modules.dagger-dang-sdk.as-sdk.modules]]
path = ".dagger/modules/focus"

[modules.focus]
source = ".dagger/modules/focus"
